name: "Build/Publish Gradle Module"
description: "Build, test, release, and publish a single module via gradle"
inputs:
  module:
    required: true
    description: "which module to build and publish"
  skip_release:
    default: "false"
    required: false
    description: whether or not to skip the axion plugin release step (should be true for all sub-modules, eg responsive-test-utils)
  OSSRH_USER:
    required: true
    description: "the OSSRH user (found in the 'secrets' context)"
  OSSRH_PASSWORD:
    required: true
    description: "the OSSRH password (found in the 'secrets' context)"
  SIGNING_KEY:
    required: true
    description: "the signing key (found in the 'secrets' context)"
  SIGNING_PASSWORD:
    required: true
    description: "the signing key password (found in the 'secrets' context)"

runs:
  using: composite
  steps:
    - name: "Gradle: Build & Test"
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :${{ inputs.module }}:build

    - name: "Gradle: Release Version"
      if: ${{ inputs.skip_release == 'false' }}
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :${{ inputs.module }}:release

    - name: "Gradle: Publish Artifacts"
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :${{ inputs.module }}:publish # publish to both S3 and Sonatype OSSRH
      env:
        OSSRH_USER: ${{ inputs.OSSRH_USER }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        SIGNING_KEY: ${{ inputs.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ inputs.SIGNING_PASSWORD }}